# apiVersion: argoproj.io/v1alpha1     
# kind: Rollout  
# metadata:
#   name: rollout-bluegreen
# spec:
#   replicas: 2
#   revisionHistoryLimit: 2
#   selector:
#     matchLabels:
#       app: rollout-bluegreen
#   template:
#     metadata:
#       labels:
#         app: rollout-bluegreen
#     spec:
#       containers:
#       - name: rollouts-demo
#         # image: argoproj/rollouts-demo:blue
#         # image: argoproj/rollouts-demo:green
#         image: argoproj/rollouts-demo:yellow
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#   strategy:
#     blueGreen: 
#       activeService: rollout-bluegreen-active 
#       previewService: rollout-bluegreen-preview
#       autoPromotionEnabled: false
apiVersion: argoproj.io/v1alpha1     
kind: Rollout  
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
#         image: argoproj/rollouts-demo:blue
#         image: argoproj/rollouts-demo:green
        image: argoproj/rollouts-demo:yellow
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active 
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
